apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:bionic
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 300; done"
